Ext.define('SupplierApp.model.FiscalDocuments', {
    extend: 'Ext.data.Model',
    fields: [
				{name:  'id'},
				{name:  'folio'},
				{name:  'serie'},
				{name:  'uuidFactura'},
				{name:  'uuidPago'},
				{name:  'uuidNotaCredito'},
				{name:  'type'},
				{name:  'addressNumber'},
				{name:  'supplierName'},
				{name:  'amount'},
				{name:  'subtotal'},
				{name:  'descuento'},
				{name:  'impuestos'},
				{name:  'rfcEmisor'},
				{name:  'rfcReceptor'},
				{name:  'moneda'},
				{name:  'centroCostos'},
				{name:  'conceptoArticulo'},
				{name:  'companyFD'},
				{name:  'invoiceDate', type: 'date', dateFormat: 'c'},
				{name:  'status'},
				{name:  'invoiceUploadDate', type: 'date', dateFormat: 'c'},
				{name:  'paymentDate'},
				{name:  'creditNoteUploadDate'},
				{name:  'transferDate', type: 'date', dateFormat: 'c'},
				{name:  'transferStatus'},
				{name:  'orderNumber'},
				{name:  'orderType'},
				{name:  'orderCompany'},				
				{name:  'currentApprover'},
				{name:  'nextApprover'},
				{name:  'approvalStatus'},
				{name:  'approvalStep'},
				{name:  'notePayment'},
				{name:  'conceptTotalAmount'},
				{name:  'advancePayment'},
				{name:  'emailApprover'},
				{name:  'zonaTpimp'}
        ]
});
