Ext.define('SupplierApp.model.PurchaseOrderDetail', {
    extend: 'Ext.data.Model',
    fields: [
			{name:  'id'},
			{name:  'itemNumber'},
			{name:  'altItemNumber'},
			{name:  'itemDescription'},
			{name:  'lineNumber'},
			{name:  'lineStatus'},
			{name:  'lotNumber'},
			{name:  'quantity'},
			{name:  'status'},
			{name:  'location'},
			{name:  'lineType'},
			{name:  'received'},
			{name:  'pending'},
			{name:  'uom'},
			{name:  'unitCost'},
			{name:  'extendedPrice'},
			{name:  'amuntReceived'},
			{name:  'glOffSet'},
			{name:  'currency'},
			{name:  'rejected'},
			{name:  'amount'},
			{name:  'reason'},
			{name:  'codigoSat'},
			{name:  'notes'},
			{name:  'receptionDate', type: 'date', dateFormat: 'c'},
			{name:  'lotExpirationDate', type: 'date', dateFormat: 'c'},
			{name:  'receptionBy'},
			{name:  'transferDate'},
			{name:  'transferStatus'},
			{name:  'orderCompany'},
			{name:  'orderNumber'},
			{name:  'orderType'},
			{name:  'accountId'},
			{name:  'openAmount'},
			{name:  'toReceive'},
			{name:  'toReject'},
			{name:  'taxCode'},
			{name:  'taxable'},
			{model: 'SupplierApp.model.Tolerances', name: 'tolerances', mapping:'tolerances', convert:modelNull},
			{model: 'SupplierApp.model.PurchaseOrderNotes', name: 'purchaseOrderNotes', mapping:'purchaseOrderNotes',type: 'auto'},
			{name:  'receiptType'},
			{name:  'objectAccount'}
        ]
});