Ext.define('SupplierApp.model.Supplier', {
    extend: 'Ext.data.Model',
    
    fields: [
			{name: 'id'},
			{name: 'addresNumber'},
			{name: 'email'},
			{name: 'ticketId'},
			{name: 'currentApprover'},
			{name: 'nextApprover'},
			{name: 'approvalStatus'},
			{name: 'approvalStep'},
			{name: 'steps'},
			{name: 'rejectNotes'},
			{name: 'approvalNotes'},
			{name: 'fechaSolicitud', type: 'date', dateFormat: 'c'},
			{name: 'fechaAprobacion', type: 'date', dateFormat: 'c'},
			{name: 'regiones'},
			{name: 'categorias'},
			{name: 'categoriaJDE'},
			{name: 'cuentaBancaria'},
			{name: 'diasCredito'},
			{name: 'tipoMovimiento'},
			{name: 'compradorAsignado'},
			{name: 'fileList'},
			{name: 'name'},
			{name: 'razonSocial'},
			{name: 'giroEmpresa'},
			{name: 'rfc'},
			{name: 'emailSupplier'},
			{name: 'industryType'},
			{name: 'calleNumero'},
			{name: 'colonia'},
			{name: 'codigoPostal'},
			{name: 'delegacionMnicipio'},
			{name: 'estado'},
			{name: 'country'},
			{name: 'webSite'},
			{name: 'telefonoDF'},
			{name: 'faxDF'},
			{name: 'nombreContactoCxC'},
			{name: 'emailContactoCxC'},
			{name: 'apellidoPaternoCxC'},
			{name: 'apellidoMaternoCxC'},
			{name: 'telefonoContactoCxC'},
			{name: 'cargoCxC'},
			{name: 'faxCxC'},
			{name: 'taxAreaCxC'},
			{name: 'taxExpl2CxC'},
			{name: 'pmtTrmCxC'},
			{name: 'payInstCxC'},
			{name: 'currCodeCxC'},
			{name: 'catCode15'},
			{name: 'catCode27'},
			{name: 'industryClass'},
			{name: 'emailCxP01'},
			{name: 'nombreCxP01'},
			{name: 'telefonoCxP01'},
			{name: 'emailCxP02'},
			{name: 'nombreCxP02'},
			{name: 'telefonoCxP02'},
			{name: 'emailCxP03'},
			{name: 'nombreCxP03'},
			{name: 'telefonoCxP03'},
			{name: 'emailCxP04'},
			{name: 'nombreCxP04'},
			{name: 'telefonoCxP04'},
			{name: 'numeroIdentificacion'},
			{name: 'nombreRL'},
			{name: 'apellidoPaternoRL'},
			{name: 'apellidoMaternoRL'},
			{name: 'bankTitleRepName'},
			{name: 'bankName'},
			{name: 'cuentaClabe'},
			{name: 'bankAccountNumber'},
			{name: 'swiftCode'},
			{name: 'ibanCode'},
			{name: 'glClass'},
			{name: 'bankTransitNumber'},
			{name: 'custBankAcct'},
			{name: 'controlDigit'},
			{name: 'description'},
			{name: 'checkingOrSavingAccount'},
			{name: 'rollNumber'},
			{name: 'bankAddressNumber'},
			{name: 'bankCountryCode'},
			{name: 'nombreBanco'},
			{name: 'formaPago'},
			{name: 'nombreContactoPedidos'},
			{name: 'emailContactoPedidos'},
			{name: 'telefonoContactoPedidos'},
			{name: 'nombreContactoVentas'},
			{name: 'emailContactoVentas'},
			{name: 'telefonoContactoVentas'},
			{name: 'nombreContactoCxC'},
			{name: 'emailContactoCxC'},
			{name: 'telefonoContactoCxC'},
			{name: 'nombreContactoCalidad'},
			{name: 'emailContactoCalidad'},
			{name: 'telefonoContactoCalidad'},
			{name: 'puestoCalidad'},
			{name: 'direccionPlanta'},
			{name: 'direccionCentroDistribucion'},
			{name: 'tipoProductoServicio'},
			{name: 'riesgoCategoria'},
			{name: 'observaciones'},
			{name: 'diasCreditoActual'},
			{name: 'diasCreditoAnterior'},
			{name: 'tasaIva'},
			{name: 'taxRate'},
			{name: 'explCode1'},
			{name: 'invException'},
			{name: 'paymentMethod'},
			{name: 'supplierType'},
			{name: 'emailComprador'},
			{name: 'currencyCode'},
			{name: 'fisicaMoral'},
			{name: 'supplierType'},
			{name: 'taxId'},
			{name: 'tipoIdentificacion'},
			{name: 'ukuid'},
	    	{name: 'outSourcing', type:'boolean'},
	    	{name: 'outSourcingAccept', type:'boolean'},
	    	{name: 'outSourcingMonthlyAccept', type:'boolean'},
	    	{name: 'outSourcingBimonthlyAccept', type:'boolean'},
	    	{name: 'outSourcingQuarterlyAccept', type:'boolean'},    	
	    	{name: 'supplierWithoutOC', type:'boolean'},
	    	{name: 'supplierWithOC', type:'boolean'},	    	
	    	{name: 'outSourcingRecordDate', type: 'date', dateFormat: 'c'},
	    	//Campos SEPASA
	    	{name: 'regimenFiscal'},
			{name: 'codigoTriburario'},
			{name: 'curp'},
			{name: 'nombreCxP05'},
			{name: 'emailCxP05'},
			{name: 'nombreCxP06'},
			{name: 'emailCxP06'},
			{name: 'nombreCxP07'},
			{name: 'emailCxP07'},
			{name: 'searchType'},
			{name: 'multPmts'},
			{name: 'catCode17'},
			{name: 'catCode21'},
			{name: 'catCode29'},
			{name: 'creditMessage'},
			{name: 'city'},
			{name: 'dischargeApplicant'},
			{name: 'changeTicket'},
			
	    	
        ],

        proxy: {
            type: 'ajax',
            api: {
                read: 'supplier/view.action',
                create: 'newRegister/save.action',
                update: 'public/update.action'
            },
            reader: {
                type: 'json',
                root: 'data',
                successProperty: 'success'
            },
            writer: {
            	type: 'json',
                writeAllFields: true,
                encode: false
            }
        }
});